### PR TITLE
Update kafka version to include client side gzip leak fix

### PR DESCRIPTION
**Pull request by mridulm**
+CC @jerryshao, @bikassaha

### CODE REVIEW

**Comment by bikassaha** [comment]
lgtm

**Comment by mridulm** [comment]
Hmm, I cant merge this in ... private repo of @jerryshao and not under hwx :-)

**Comment by bikassaha** [comment]
https://github.com/hortonworks-spark/skc

**Comment by bikassaha** [comment]
Does this build with 0.10.1 or similar API issues in test as with 0.10.2?

**Comment by mridulm** [comment]
@bikassaha What is the difference between skc and this repo ? If skc is the source of truth, I can re-submit this pr there.

It builds fine, unlike with 0.10.2.0
The build looks flakey though, I saw it failing in a couple of tests.
```
DirectKafkaStreamSuite:
- basic stream receiving with multiple topics and smallest starting offset *** FAILED *** (1 minute, 43 seconds)
  The code passed to eventually never returned normally. Attempted 110 times over 1.6715726344999997 minutes. Last failure message: 0 did not equal 46 didn't get expected number of messages, messages:
  . (DirectKafkaStreamSuite.scala:152)
- pattern based subscription *** FAILED *** (1 minute, 41 seconds)
  The code passed to eventually never returned normally. Attempted 110 times over 1.6714693950333335 minutes. Last failure message: 0 did not equal 41 didn't get expected number of messages, messages:
  . (DirectKafkaStreamSuite.scala:218)
```

@jerryshao is this a known issue ?

**Comment by bikassaha** [comment]
skc is the official one. maybe this one was for initial dev work.

**Comment by mridulm** [comment]
Ah ok, then I will mentioned that in the hipchat room as well.

**Pull request closed without merging**
